#!/usr/bin/env python3
"""Build one atomic SQL transaction for a validated Pocket Cosmos publish bundle."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def sql_text(value) -> str:
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def sql_json(value) -> str:
    text = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return sql_text(text) + "::jsonb"


def sql_int(value) -> str:
    return "NULL" if value is None else str(int(value))


def statement_for(item: dict) -> str:
    q = item["question"]
    v = item["version"]
    qid = str(q["id"])
    digest = str(v["contentHash"])

    lines = [
        f"-- {qid}",
        "INSERT INTO public.questions",
        "  (id, practice_set_id, legacy_question_id, status, position, updated_at)",
        "VALUES",
        f"  ({sql_text(qid)}, {sql_text(q['practiceSetId'])}, {sql_text(q['legacyQuestionId'])}, "
        f"{sql_text(q.get('status') or 'active')}, {sql_int(q['position'])}, now())",
        "ON CONFLICT (id) DO UPDATE SET",
        "  practice_set_id = EXCLUDED.practice_set_id,",
        "  legacy_question_id = EXCLUDED.legacy_question_id,",
        "  status = EXCLUDED.status,",
        '  "position" = EXCLUDED."position",',
        "  updated_at = now();",
        "",
        "INSERT INTO public.question_versions",
        "  (question_id, version, stem, choices, answer, explanation, metadata, source_year, source_ref, content_hash)",
        "SELECT",
        f"  {sql_text(qid)},",
        f"  COALESCE((SELECT MAX(version) + 1 FROM public.question_versions WHERE question_id = {sql_text(qid)}), 1),",
        f"  {sql_text(v['stem'])},",
        f"  {sql_json(v.get('choices') or [])},",
        f"  {sql_json(v.get('answer') or {})},",
        f"  {sql_text(v.get('explanation'))},",
        f"  {sql_json(v.get('metadata') or {})},",
        f"  {sql_int(v.get('sourceYear'))},",
        f"  {sql_text(v.get('sourceRef'))},",
        f"  {sql_text(digest)}",
        "WHERE NOT EXISTS (",
        "  SELECT 1 FROM public.question_versions",
        f"  WHERE question_id = {sql_text(qid)} AND content_hash = {sql_text(digest)}",
        ");",
        "",
    ]

    for asset in item.get("assets") or []:
        lines += [
            "INSERT INTO public.question_assets",
            "  (question_version_id, role, storage_bucket, storage_path, choice_key, sort_order, metadata)",
            "SELECT",
            "  qv.id,",
            f"  {sql_text(asset['role'])},",
            f"  {sql_text(asset['storageBucket'])},",
            f"  {sql_text(asset['storagePath'])},",
            f"  {sql_text(asset.get('choiceKey'))},",
            f"  {sql_int(asset.get('sortOrder', 0))},",
            f"  {sql_json(asset.get('metadata') or {})}",
            "FROM public.question_versions qv",
            f"WHERE qv.question_id = {sql_text(qid)} AND qv.content_hash = {sql_text(digest)}",
            "ON CONFLICT (question_version_id, role, storage_bucket, storage_path) DO NOTHING;",
            "",
        ]
    return "\n".join(lines)


def build_sql(bundle: dict) -> str:
    lines = [
        "-- Generated by physics-bank-web-publisher v1.0.0",
        "-- Storage objects must be uploaded successfully before this transaction is executed.",
        "BEGIN;",
        "",
    ]
    for item in bundle.get("questions") or []:
        lines.append(statement_for(item))
    lines += [
        "-- Historical versions are intentionally retained.",
        "COMMIT;",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("bundle", type=Path)
    p.add_argument("--output", required=True, type=Path)
    args = p.parse_args()
    bundle = json.loads(args.bundle.read_text(encoding="utf-8"))
    sql = build_sql(bundle)
    args.output.write_text(sql, encoding="utf-8")
    print(f"Wrote transaction for {len(bundle.get('questions') or [])} question(s): {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
